GET http://restfulapi.test/api/posts

###

POST http://api-ajudai.herokuapp.com/api/donors
Content-Type: application/json

{
    "name_donor": "My brand new title",
    "email_donor": "My brand new content",
    "phone":"132123",
    "pasword":"senha123"
}

###

PUT http://restfulapi.test/api/posts/4
Content-Type: application/json

{
    "title": "My brand new title (updated)",
    "content": "My brand new content (updated)"
}

###

DELETE http://restfulapi.test/api/posts/4
