GET http://restfulapi.test/api/posts
Content-Type: application/json
###
GET http://laravel-rest.test/api/donors
Content-Type: application/json
###

POST http://laravel-rest.test/api/donors
Content-Type: application/json

{
    "name_donor": "teste-a-a-a",
    "email_donor": "1234@gmail.com",
    "phone":"1321232313342",
    "password_donor":"senha123",
}

###

PUT http://restfulapi.test/api/posts/4
Content-Type: application/json

{
    "title": "My brand new title (updated)",
    "content": "My brand new content (updated)"
}

###

DELETE http://restfulapi.test/api/posts/4
